instagram_clone/social/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views  


urlpatterns = [
    path('',views.Registration,name='Registration'),
    path('home',views.home,name='home'),
    path('Login',views.Login,name="Login"),
    path('logout',views.logout,name='logout'),
    path('profile',views.profile,name='profile'),
    path('Editprofile',views.Editprofile,name='Editprofile'),
    path('createpost', views.createpost,name='createpost'),
    path('editpost/<int:post_id>/',views.editpost,name='editpost'),
    path('likeview/<int:post_id>', views.likeview,name='likeview'),
    path('favorite/<int:post_id>', views.favorite,name='favorite'),
    path('deletepost/<int:post_id>', views.deletepost,name='deletepost'),
    path('addcomment/<int:post_id>/',views.addcomment,name='addcomment'),
    path('addstory',views.addstory,name='addstory'),
    path('viewstory/<int:str_id>',views.viewstory,name='viewstory'),
    path('favoritepostlist',views.favoritepostlist,name='favoritepostlist'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('following_users',views.following_users,name='following_users'),
    path('follower_list',views.follower_list,name='follower_list'),
    path('follow_user/<int:user_id>',views.follow_user,name='follow_user'),
]

instagram_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('social.urls')),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", views.Registration, name="Registration"),
    path("login/", views.login, name="login"),
    path('logout/',views.logout,name='logout'),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("index/", views.index, name="index"),
    path("newpost/", views.NewPost, name="newpost"),
    path("postdetail/<uuid:post_id>", views.postDetail, name="postdetail"),
    path('editpost/<uuid:post_id>/',views.editpost,name='editpost'),
    path('favorite/<uuid:post_id>', views.favorite,name='favorite'),
    path("likeview/<uuid:post_id>", views.likeview, name="likeview"),
    path("comment/<uuid:post_id>", views.comment, name="comment"),
    path("profile/<username>", views.UserProfile, name="profile"),
    path('Editprofile',views.Editprofile,name='Editprofile'),
    path("follow/<username>", views.follow, name="follow"),
    path('addstory/',views.addstory,name='addstory'),
    path('archive/',views.archive,name='archive'),
    path('inbox/',views.inbox,name='inbox'),
    path('direct/<username>',views.Directs,name='direct'),
    path('sendmessage/',views.SendMessage, name='sendmessage'),
    path('searchuser/',views.UserSearch, name='searchuser'),
    path('newmessage/<username>',views.NewMessage, name='newmessage'),
]

instagram_clone/social/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone



class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='post')
    image=models.ImageField(upload_to='images/')
    caption=models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)
    likes=models.IntegerField(default=0)


    def __str__(self):
        return self.user.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(upload_to='images/', default='')
    created_on = models.DateField(default=datetime.date.today)
    updated_on = models.DateField(default=datetime.date.today)
    favorite=models.ManyToManyField(Post)
    following=models.ManyToManyField('self', symmetrical=False, related_name='follower',blank=True)

    def __str__(self):
        return self.user.username



class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    text=models.CharField(max_length=1000)
    created_date=models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.user.username
    
class Story(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    file=models.ImageField(upload_to='images/')
    profile=models.ForeignKey(Profile,on_delete=models.CASCADE)
    created_at=models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.user.username

class like(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(Post,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    

instagram_clone/social/forms.py
from django import forms
from .models import Post,Story,Profile
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password']

    def clean_firstname(self):
        firstname=self.cleaned_data.get('first_name')
        if not firstname:
            raise forms.ValidationError("Firstname is required")
        return firstname
        
    def clean_lastname(self):
        lastname=self.cleaned_data.get('last_name')
        if not lastname:
            raise forms.ValidationError("lastname is required")
        return lastname
        
    def clean_email(self):
        email=self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("email is required")
        return email
    
class EditProfile(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['bio','profile_picture']
    
    def clean_bio(self):
        bio=self.cleaned_data.get('bio')
        if not bio:
            raise forms.ValidationError('field required')
        return bio

    def clean_profile(self):
        profile_picture=self.cleaned_data.get('profile_picture')
        if not profile_picture:
            raise forms.ValidationError('field required')
        return profile_picture

class postform(forms.ModelForm):
    class Meta:
        model=Post
        fields=['image','caption']
    
    def clean_image(self):
        image=self.cleaned_data.get('image')
        if not image:
            raise forms.ValidationError('Fields Required')
        return image

    def clean_caption(self):
        caption=self.cleaned_data.get('caption')
        if not caption:
            raise forms.ValidationError("caption Required")
        return caption
    
class postedit(forms.ModelForm):
    class Meta:
        model=Post
        fields=['image','caption']

    def clean_image(self):
        image=self.cleaned_data.get('image')
        if not image:
            raise forms.ValidationError('Fields Required')
        return image

    def clean_caption(self):
        caption=self.cleaned_data.get('caption')
        if not caption:
            raise forms.ValidationError("caption Required")
        return caption

class storyform(forms.ModelForm):
    class Meta:
        model=Story
        fields=['file']
    
    def clean_file(self):
        file=self.cleaned_data.get('file')
        if not file:
            raise forms.ValidationError('field required')
        return file

instagram_clone/social/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib import messages
from .models import Profile,Post,Comment,like,Story
from django.contrib.auth.decorators import login_required
from .forms import postform,postedit,storyform,RegistrationForm,EditProfile
from django.urls import reverse
import datetime
from django.db.models import Q



def Registration(req):
    if req.method=='POST':
        form=RegistrationForm(req.POST)
        if form.is_valid():
            form.save()
            messages.success(req,"Successfully Registered")
            return redirect('Login')
        else:
            messages.error(req,'All fields are required')
    else:
        form=RegistrationForm()
    return render(req,'Registration.html',{'form':form})
        
def Login(req):
    if req.method=='POST':
        username=req.POST.get('username')
        password=req.POST.get('password')

        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(req,user)
            return redirect('home')
        else:
            messages.error(req,'Invalid Credential')
            return redirect('Login')
    else:
        return render(req,'Login.html')
    
def logout(req):
    auth.logout(req)
    return redirect('/')

 
def profile(req):
    user=req.user
    try:
        profile=Profile.objects.get(user=user)
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=user)
    posts=Post.objects.filter(user__username=user.username)
    postcount=posts.count()
    following=profile.following.count()
    follower=profile.follower.count()
    return render(req,'Profile.html',{'profile':profile,'posts':posts,'postcount':postcount,'following':following,'follower':follower})

def Editprofile(req):
    profile=Profile.objects.get(user=req.user)
    if req.method=='POST':
        form=EditProfile(req.POST,req.FILES,instance=profile)
        if form.is_valid():
            form.save()
            messages.success(req,"Successfully Updated")
            return redirect('profile')
        else:
            messages.error(req,'All fields required')
    else:
        form=EditProfile(instance=profile)
    return render(req,'Editprofile.html',{'form':form})


def home(req):
    user=req.user
    posts=Post.objects.all()
    time = datetime.datetime.now() - datetime.timedelta(hours=24)
    stories=Story.objects.filter(created_at__gte=time)
    print(stories)
    profile,created=Profile.objects.get_or_create(user=user)
    allprofile=Profile.objects.exclude(user__is_superuser=True).exclude(user=user).values('user__username','profile_picture','user__id')
    print([allprofile])
    return render(req,'home.html',{'posts':posts,'profile':profile,'stories':stories,'allprofile':allprofile})

def createpost(req):
    if req.method=='POST':
        form=postform(req.POST,req.FILES)
        if form.is_valid():
            Post=form.save(commit=False)
            Post.user=req.user
            Post.save()
            messages.success(req,'Post Created Successfully')
            return redirect('home')
        else:
            messages.error(req,'Invalid form data')
            return render(req,'postform.html',{'form':form})
    else:
        form=postform()
        return render(req,'postform.html',{'form':form})

def deletepost(req,post_id):
    user=req.user
    try:
        post=Post.objects.get(id=post_id,user=user)
        post.delete()
        messages.success(req,'Deleted Successfully')
        return redirect('home')
    except:
        messages.success(req,'you are not authorized to perform deletetion')
        return redirect('home')

def editpost(req,post_id):
    post=Post.objects.get(id=post_id)
    if req.method=='POST':
       form=postedit(req.POST,req.FILES,instance=post)
       if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form=postedit(instance=post)
    return render(req,'editpost.html',{'form':form ,'post':post})

@login_required
def addcomment(req, post_id):
    if req.method == 'POST':
        post = Post.objects.get(id=post_id)
        text = req.POST.get('text')
        if text:
            comment = Comment.objects.create(
                post=post,
                user=req.user,
                text=text
            )
            comment.save()
            return redirect('home')
    return render(req, 'home.html', {'post_id': post_id})
    
def addstory(req):
    user = req.user
    profile = Profile.objects.get(user=user)  
    if req.method == 'POST':
        form = storyform(req.POST, req.FILES)
        if form.is_valid():
            story = form.save(commit=False)
            story.user = user
            story.profile = profile
            story.save()
            messages.success(req, 'Story added successfully')
            return redirect('home')
        else:
            messages.error(req, 'Something went wrong')
            return render(req, 'Story.html', {'form': form})
    else:
        form = storyform()
        return render(req, 'Story.html', {'form': form})

def viewstory(req,str_id):
    stories=Story.objects.get(id=str_id)
    return render(req,'viewstory.html',{'stories':stories})

def likeview(req,post_id):
    user=req.user
    post=Post.objects.get(id=post_id)
    current_likes=post.likes
    liked=like.objects.filter(user=user,post=post).count()
    if not liked:
        liked=like.objects.create(user=user,post=post)
        current_likes=current_likes+1
    else:
        liked=like.objects.filter(user=user,post=post).delete()
        current_likes=current_likes-1
    post.likes=current_likes
    post.save()
    return redirect(reverse('home'))

def favorite(req,post_id):
    user=req.user
    post=Post.objects.get(id=post_id)
    profile=Profile.objects.get(user=user)
    if profile.favorite.filter(id=post_id).exists():
        profile.favorite.remove(post)
    else:
        profile.favorite.add(post)
    return redirect(reverse('home'))

def favoritepostlist(req):
    user=req.user
    profile=user.profile
    favorite_post=profile.favorite.all()

    return render(req,'favoritepost.html',{'favorite_post':favorite_post})
def follow_user(req,user_id):
    user=req.user
    profile=Profile.objects.get(user=user)
    follow=Profile.objects.get(user=user_id)
    if profile.following.filter(user=user_id).exists():
        profile.following.remove(follow)
    else:
        profile.following.add(follow)
    return redirect('profile')

def following_users(req):
    user=req.user
    profile=Profile.objects.get(user=user)
    following=profile.following.all()
    return render(req,'Follow.html',{'following':following})

def follower_list(req):
    user=req.user
    profile=Profile.objects.get(user=user)
    follower=profile.follower.all()
    return render(req,'FollowerList.html',{'follower':follower})

social/templates/Registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
        <link rel="stylesheet" href="{%static 'assets2/style.css' %}">
        <title>Instagram Registratin Form</title>
    </head>

    <body>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                    <script>alert("{{message}}")</script>{% endif %}
            {% endfor %}
        {% endif %}
        <div id="wrapper">
            <div class="container">
                <div class="phone-app-demo"></div>
                <div class="form-data">
                    <form  method="POST" class="reg">
                        <div class="logo">
                            <img src="{% static 'assets2/images/logo.png' %}" alt="logo">
                        </div>
                        {% csrf_token %}
                        {{form}}
                        <button class="form-btn" type="submit">Register</button>
                        <span class="has-separator">Or</span>
                        <a class="facebook-login" href="#">
                            <i class="fab fa-facebook-square"></i> Log in with Facebook
                        </a>
                        <a class="password-reset" href="#">Forgot password?</a>
                    </form>
                    <div class="sign-up">
                        have an account? <a href="login/">Login</a>
                    </div>
                    <div class="get-the-app">
                        <span>Get the app.</span>
                        <div class="badges">
                            <img src="{% static 'assets2/images/app-store.png' %}" alt="app-store badge">
                            <img src="{% static 'assets2/images/google-play.png' %}" alt="google-play badge">
                        </div>
                    </div>
                </div>
            </div>

            <footer>
                <div class="container">
                    <nav class="footer-nav">
                        <ul>
                            <li>
                                <a href="#">About us</a>
                            </li>
                            <li>
                                <a href="#">Support</a>
                            </li>
                            <li>
                                <a href="#">Press</a>
                            </li>
                            <li>
                                <a href="#">Api</a>
                            </li>
                            <li>
                                <a href="#">Jobs</a>
                            </li>
                            <li>
                                <a href="#">Privacy</a>
                            </li>
                            <li>
                                <a href="#">Terms</a>
                            </li>
                            <li>
                                <a href="#">Directory</a>
                            </li>
                            <li>
                                <a href="#">Profiles</a>
                            </li>
                            <li>
                                <a href="#">Hashtags</a>
                            </li>
                            <li>
                                <a href="#">Languages</a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright-notice">
                        &copy 2019 Instagram
                    </div>
                </div>
            </footer>

        </div>

    </body>

</html>

social/templates/editpost.html
{% extends "base.html" %}

{% block content %}
    <div class="edit" style="margin-top: 100px;">
        <div class="editform">
            <form action="" method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {{form}}
                <input type="submit" value='save'>
            </form>
        </div>
    </div>
{% endblock content %}

social/templates/editprofile.html
{% extends "sidebar.html" %}
{% load static %}

{% block container %}
    <div class="Editprofile">
        <form action="" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}

            <div class="profile-picture-section">
                <label for="id_profile_picture">Profile Picture:</label>
                {% if profile_picture %}
                    <img src="{{ profile.profile_picture.url }}" alt="Current Image" class="current-image">
                {% else %}
                    <img src="{% static 'assets1/default-user.png' %}" alt="Current Image" class="current-image">
                {% endif %}
                {{ form.profile_picture }}
            </div>

            <div class="bio-section">
                <label for="id_bio">Bio:</label>
                {{ form.bio }}
            </div>

            <input type="submit" value="Save">
        </form>
    </div>
{% endblock container %}

social/templates/inbox.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        body {
            margin-top: 20px;
        }

        .chat-online {
            color: #34ce57
        }

        .chat-offline {
            color: #e4606d
        }

        .chat-messages {
            display: flex;
            flex-direction: column;
            max-height: 800px;
            overflow-y: scroll
        }

        .chat-message-left,
        .chat-message-right {
            display: flex;
            flex-shrink: 0
        }

        .chat-message-left {
            margin-right: auto
        }

        .chat-message-right {
            flex-direction: row-reverse;
            margin-left: auto
        }

        .py-3 {
            padding-top: 1rem !important;
            padding-bottom: 1rem !important;
        }

        .px-4 {
            padding-right: 1.5rem !important;
            padding-left: 1.5rem !important;
        }

        .flex-grow-0 {
            flex-grow: 0 !important;
        }

        .border-top {
            border-top: 1px solid #dee2e6 !important;
        }
    </style>
</head>
<br><br>
<main class="conetent">
    <div class="container p-0">

        <h1 class="h3 mb-3">Messages</h1>

        <div class="card">
            <div class="row g-0">
                <div class="col-12 col-lg-12 col-xl-3 border-right chat-messages">

                    <div class="px-4 d-none d-md-block">
                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1">
                                <a href="{% url 'searchuser' %}" class="btn btn-success mt-4 mb-4">New Message</a>
                            </div>
                        </div>
                    </div>
                    {% for message in messages %}
                    <a href="{% url 'direct' message.user.username %}"
                        class="list-group-item list-group-item-action border-0 {% if active_direct == message.user.username %}active{% endif %}">
                        <div class="badge bg-success float-left"></div>
                        <div class="d-flex align-items-start pb-2">

                            <img src="{{ message.user.profile.profile_picture.url }}" class="rounded-circle mr-1"
                                alt="img" width="40" height="40">
                            <div class="flex-grow-1 ml-6">
                                <b>{{message.user.first_name}} {{message.user.last_name}}</b>
                                <div class="small"><span class="fas fa-circle chat-online"></span>
                                    @{{message.user.username}}</div>
                            </div>
                        </div>
                    </a>
                    {% endfor %}

                    <hr class="d-block d-lg-none mt-1 mb-0">
                </div>
                <div class="col-12 col-lg-7 col-xl-9">
                    <div class="py-2 px-4 border-bottom d-none d-lg-block">
                        <div class="d-flex align-items-center py-1">
                            <!-- <div class="position-relative">
								<img src="https://bootdey.com/img/Content/avatar/avatar3.png" class="rounded-circle mr-1" alt="Sharon Lessman" width="40" height="40">
							</div>
							<div class="flex-grow-1 pl-3">
								<strong>Sharon Lessman</strong>
								<div class="text-muted small"><em>Typing...</em></div>
							</div> -->
                            <div>
                                <button class="btn btn-primary btn-lg mr-1 px-3"><svg xmlns="http://www.w3.org/2000/svg"
                                        width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                        class="feather feather-phone feather-lg">
                                        <path
                                            d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z">
                                        </path>
                                    </svg></button>
                                <button class="btn btn-info btn-lg mr-1 px-3 d-none d-md-inline-block"><svg
                                        xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-video feather-lg">
                                        <polygon points="23 7 16 12 23 17 23 7"></polygon>
                                        <rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect>
                                    </svg></button>
                                <button class="btn btn-light border btn-lg px-3"><svg xmlns="http://www.w3.org/2000/svg"
                                        width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                        class="feather feather-more-horizontal feather-lg">
                                        <circle cx="12" cy="12" r="1"></circle>
                                        <circle cx="19" cy="12" r="1"></circle>
                                        <circle cx="5" cy="12" r="1"></circle>
                                    </svg></button>
                            </div>
                        </div>
                    </div>

                    <div class="position-relative">
                        <div class="chat-messages p-4">

                            {% for direct in directs %}
                            {% if direct.sender == request.user %}
                            <div class="chat-message-right pb-2">
                                <div>
                                    <a href=""><img src="{{ direct.sender.profile.profile_picture.url }}"
                                            class="rounded-circle mr-1" alt="img" width="40" height="40"></a>
                                    <div class="text-muted small text-nowrap mt-2"
                                        style="font-size:10px; color: rgba(180, 180, 180, 0);">
                                        <p style="font-size:10px; color: black;">{{direct.date|date:"d M, Y"}}</p>
                                    </div>

                                </div>
                                <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
                                    {{direct.body}}
                                </div>
                            </div>
                            {% else %}
                            <div class="chat-message-left pb-2">
                                <div>
                                    <a href=""><img src="{{ direct.sender.profile.profile_picture.url }}"
                                            class="rounded-circle mr-1" alt="img" width="40" height="40"></a>
                                    <div class="text-muted small text-nowrap mt-2"
                                        style="font-size:10px; color: rgba(180, 180, 180, 0);">
                                        <p style="font-size:10px; color: black;">{{direct.date|date:"d M, Y"}}</p>
                                    </div>

                                </div>
                                <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
                                    <!-- <div class="font-weight-bold mb-1">Sharon Lessman</div> -->
                                    {{direct.body}}
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}


                        </div>
                    </div>


                    <div class="flex-grow-0 py-3 px-4 border-top">
                        <form method="POST" action="{% url 'sendmessage' %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="hidden" name="to_user" id="" value="{{active_direct}}">
                                <input name="body" type="text" class="form-control" placeholder="Type your message">
                                <button class="btn btn-primary" type="submit">Send</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</main>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</html>
{% endblock content %}

social/templates/password_reset_complete.html
<h2>Password reset complete</h2>
<p>Your password has been set. You can now <a href="{% url 'login' %}">log in</a>.</p>

social/templates/password_reset_done.html
<h2>Password reset sent</h2>
<p>We have sent you an email with instructions to reset your password.</p>

social/templates/story.html
{% extends "base.html" %}
{% block content %}
    <div class="Stories" style="margin-top: 20vh;">
        <div class="story">
            <form action="{% url 'addstory' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <input type="submit">
            </form>
        </div>
    </div>
{% endblock content %}